const actionTypes = {
  GET_CUSTOMERS: 'GET_CUSTOMERS',
  ADD_CUSTOMERS: 'ADD_CUSTOMERS',
  UPDATE_CUSTOMERS: 'UPDATE_CUSTOMERS',
  DELETE_CUSTOMERS: 'DELETE_CUSTOMERS',
};

export default actionTypes;
