const actionTypes = {
  GET_CUSTOMERS: 'GET_CUSTOMERS',
  ADD_CUSTOMER: 'ADD_CUSTOMER',
  UPDATE_CUSTOMER: 'UPDATE_CUSTOMER',
  DELETE_CUSTOMER: 'DELETE_CUSTOMER',

  //Notification
  NOTIFICATION:'NOTIFICATION',
};

export default actionTypes;
