const actionTypes = {
  //Customer
  GET_CUSTOMERS: 'GET_CUSTOMERS',
  ADD_CUSTOMER: 'ADD_CUSTOMER',
  UPDATE_CUSTOMER: 'UPDATE_CUSTOMER',
  DELETE_CUSTOMER: 'DELETE_CUSTOMER',
  DELETE_MULTIPLE_CUSTOMER: 'DELETE_MULTIPLE_CUSTOMER',
};

export default actionTypes;
